name: Delete test keys
on:
  schedule:
    - cron: "0 1,6,11,16,21 * * *"
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install requests
      - run: python delete_test.py